version: '3.8'

services:
    maxima-database:
        image: postgres
        environment: 
            - POSTGRES_USER=MaximaDatabase
            - POSTGRES_PASSWORD=1RSMa27EaFDj
            - POSTGRES_DB=mecommerce
        volumes:
            - db-data:/var/lib/postgresql/data/
        networks: 
            maxima-network:
                aliases: 
                    - data.maximatech.com.br
    maxima-redis:
        image: redis
        environment:
            - REDIS_REPLICATION_MODE=master
        volumes:
            - redis-data:/var/lib/redis
        networks: 
            maxima-network:
                aliases: 
                    - redis.maximatech.com.br
        ports:
            - "6379"
    maxima-config:
        image: maxima-config
        build: ./backend/config/
        networks: 
            maxima-network:
                aliases: 
                    - config.maximatech.com.br
        expose: 
            - "8091"
    maxima-discovery:
        image: maxima-discovery
        build: ./backend/discovery
        depends_on:
            - "maxima-redis"
            - "maxima-config"
        networks: 
            maxima-network:
                aliases: 
                    - discovery.maximatech.com.br
        expose: 
            - "8092"
    maxima-gateway:
        image: maxima-gateway
        build: ./backend/gateway
        depends_on:
            - "maxima-config"
            - "maxima-discovery"
            - "maxima-redis"
        networks: 
            maxima-network:
                aliases: 
                    - gateway.maximatech.com.br    
        expose:
            - "8080"
        ports: 
            - "8080:8080"
    maxima-api:
        image: maxima-api
        build: ./backend/api
        depends_on: 
            - "maxima-config"
            - "maxima-discovery"
            - "maxima-gateway"
            - "maxima-database"
            - "maxima-redis"
        networks: 
            maxima-network:
                aliases: 
                    - api.maximatech.com.br   
        expose:
            - "8081"
    maxima-tax:
        image: maxima-tax
        build: ./backend/tax
        depends_on: 
            - "maxima-config"
            - "maxima-discovery"
            - "maxima-gateway"
            - "maxima-database"
            - "maxima-redis"
        networks: 
            maxima-network:
                aliases: 
                    - tax.maximatech.com.br   
        expose:
            - "8082"

networks:
    maxima-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.0.0/16

volumes:
    db-data:
    redis-data: